[package]
name = "t-rex-core"
version = "0.8.0-dev"
description = "vector tile server"
repository = "https://github.com/pka/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
workspace = ".."

[lib]
doctest = false

[dependencies]
toml = "*"
fallible-iterator = "*"
r2d2 = "*"
r2d2_postgres = "*"
postgis = "~0.4.0"
protobuf = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
log = "*"
flate2 = "*"

[dependencies.postgres]
version = "*"
features = ["with-native-tls"]
