language: rust
cache: cargo

env:
  global:
    - DBCONN=postgresql://postgres@127.0.0.1/natural_earth_vectors
    # This will be part of the release tarball
    - PROJECT_NAME=t-rex
    - MAKE_DEB=yes
    - DEB_MAINTAINER="Pirmin Kalberer <pi_deb@sourcepole.ch>"
    - DEB_DESCRIPTION="t-rex vector tile server"

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: vX88w3SdgqUmWpFROgBRtR3OA89kkgExXzvD7x9Rt/8GhXgjF86q4DoiIPtk8qQneeqo3xmU0MhQlorWWCE+PhBno2M4lix0p3jCHrs3q10ez8YqGRwh88bCB6cVCBervBXi2dBkSHpJL5qc0VDtHxfJGe3dfJ75BcwNedD9nNwiuuPPy0eIZkOFpoV1QEKnwM5JdDibE24EEIaygGQbgxdG5KhSjSubL4yyFftxMbd0p12F6TVqpSDLXW34iEAjaaAdmAF3mQDUWhg/CVK/4HrLZq7dDP/m1YIcRzFlMKzxUxQSUAe27gsyN92ddbLqGE1vKgaTfY904OHbAyWTNvIVLlYp4DwSCVFMdsGsTEhfY1sok64vPEk6jzz43tds1OGvjWafzksYslyml3DSKLCG3myIGxFaobMraBhBl2m0wEv3uSt5wPfFm7iSRfQsXHQXBThJHvTIWfYLLsQmS5tnV1H3yp0HnJyUEb3gPgtiX7iTwTwBxkFS6UPPrAPbSstAq2YVdxvmxWPKiKvUw1tuy8rX/fQFR7GgEoPffQaa574gfT2Sz2f4qEnUqxVwU1S1tFHDAPNazBZoOOHPHhehxPcAMqdGWaVcdj2X5WhBceFslvpbRQahR9kTGgMBk69Qy9Xe0VveL+tdLeebTvsIh/7IAk3Iw2jB37ENwJk=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  skip_cleanup: true
  on:
    # channel to use to produce the release artifacts
    # NOTE make sure you only release *once* per target
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true

notifications:
  email:
    on_success: never
