[package]
name = "t-rex"
version = "0.6.1"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[dependencies]
toml = "*"
postgres = "*"
r2d2 = "*"
r2d2_postgres = "*"
postgis = "~0.3.0"
protobuf = "*"
nickel = "~0.8.1"
rustc-serialize = "*"
clap = "~2.10.0" # Compile error in 2.11.3
log = "*"
env_logger = "*"
time = "*"
flate2 = "*"
pbr = "*"

[dependencies.hyper]
version = "0.8.1" # Same version as nickel
default-features = false
