[package]
name = "t-rex"
version = "0.7.2-dev"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[dependencies]
toml = "*"
postgres = "*"
r2d2 = "*"
r2d2_postgres = "*"
postgis = "~0.4.0"
protobuf = "*"
nickel = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
rustc-serialize = "*"
clap = "*"
log = "*"
env_logger = "*"
time = "*"
flate2 = "*"
pbr = "*"

[dependencies.hyper]
version = "0.9.18" # Same version as nickel 0.9.0
default-features = false
