[package]
name = "t-rex"
version = "0.0.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[features]
dbtest = []

[dependencies]
postgis = "*"
protobuf = "*"
nickel = "*"
nickel_mustache = "*"
rustc-serialize = "*"
clap = "*"
log = "*"
env_logger = "*"
time = "*"

[dependencies.postgres]
version = "*"
features = ["unix_socket"]

[dependencies.hyper]
version = "0.8.1"
default-features = false
