[package]
name = "t-rex"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[features]
dbtest = []

[dependencies]
postgis = "0.2.1"
protobuf = "1.0.18"
nickel = "0.8.0"

[dependencies.postgres]
version = "0.11.4"
features = ["unix_socket"]

[dependencies.hyper]
version = "0.8.1"
default-features = false
