[package]
name = "t-rex-webserver"
version = "0.8.0-dev"
description = "vector tile server"
repository = "https://github.com/pka/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
build = "build.rs"
workspace = ".."

[dependencies]
nickel = "*"
hyper = "*"
serde_json = "*"
rustc-serialize = "*"
toml = "*"
clap = "*"
log = "*"
env_logger = "*"
open = "*"

[dependencies.t-rex-core]
path = "../t-rex-core"

[dependencies.t-rex-service]
path = "../t-rex-service"
