[package]
name = "t-rex-webserver"
version = "0.9.9"
description = "vector tile server"
repository = "https://github.com/t-rex-tileserver/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
build = "build.rs"
workspace = ".."

[lib]
doctest = false

[dependencies]
actix = { git="https://github.com/actix/actix.git" } # -> 0.6
actix-web =  { git = "https://github.com/actix/actix-web.git" } # -> 0.7
futures = "0.1"
clap = "2.31"
log = "0.4"
open = "1.2"
lazy_static = "1.0"

[dependencies.t-rex-core]
path = "../t-rex-core"

[dependencies.t-rex-service]
path = "../t-rex-service"
