[package]
name = "t-rex-service"
version = "0.8.0-dev"
description = "vector tile server"
repository = "https://github.com/pka/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
workspace = ".."

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
log = "*"
pbr = "*"

[dependencies.t-rex-core]
path = "../t-rex-core"
version = "0.7.8-dev"

[dependencies.t-rex-gdal]
path = "../t-rex-gdal"
version = "0.8.0-dev"
optional = true

[features]
with-gdal = ["t-rex-gdal"]
