[package]
name = "t-rex-gdal"
version = "0.9.9"
description = "vector tile server"
repository = "https://github.com/t-rex-tileserver/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
workspace = ".."

[lib]
doctest = false

[dependencies]
gdal = { git = "https://github.com/georust/rust-gdal.git" }
# gdal = { path = "../../rust-gdal" }
log = "*"

[dependencies.t-rex-core]
path = "../t-rex-core"
