[package]
name = "t-rex-gdal"
version = "0.8.0-dev"
description = "vector tile server"
repository = "https://github.com/pka/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
workspace = ".."

[dependencies]
gdal = { git = "https://github.com/pka/rust-gdal", branch = "t-rex", optional = true }
#gdal = { path = "../../rust-gdal" }
log = "*"

[dependencies.t-rex-core]
path = "../t-rex-core"

[features]
with-gdal = ["gdal"]
